export function configFile(projectName: string): string {
  return [
    "export default {",
    "  schemaVersion: 1,",
    `  name: ${JSON.stringify(projectName)},`,
    '  template: "internal-ops",',
    "} as const;",
    "",
  ].join("\n");
}

export function agentFile(projectName: string): string {
  return [
    `# ${projectName}`,
    "",
    "This project is organized file-first.",
    "",
    "## Working Principles",
    "",
    "- Start from the Markdown instructions in this repository.",
    "- Use the project files as the source of truth.",
    "- Keep changes scoped and easy to validate.",
    "",
    "## First Pass",
    "",
    "- Read `plico.config.ts` and `agent.md`.",
    "- Inspect `skills/`, `tools/`, `evals/`, `artifacts/`, and `memory/`.",
    "- Add project-specific instructions before expanding the scaffold.",
    "",
  ].join("\n");
}

export function triageSkillFile(): string {
  return [
    "# Triage",
    "",
    "Review incoming work items, identify the smallest safe next step, and record the outcome.",
    "",
    "Focus on the project files first, then the surrounding context.",
    "",
  ].join("\n");
}

export function toolsReadmeFile(): string {
  return [
    "# Tools",
    "",
    "Add TypeScript tool modules here when the project needs executable helpers.",
    "",
    "Keep the public contract file-first until tools are explicitly required.",
    "",
  ].join("\n");
}

export function smokeEvalFile(): string {
  return [
    "# Smoke Eval",
    "",
    "Verify the scaffold boots, validates, and presents a clear starting point.",
    "",
  ].join("\n");
}

export function memoryReadmeFile(): string {
  return [
    "# Memory",
    "",
    "Use this folder for durable project notes, decisions, and recurring context.",
    "",
  ].join("\n");
}

export function artifactsReadmeFile(): string {
  return [
    "# Artifacts",
    "",
    "Use this folder for generated outputs that belong to the project.",
    "",
  ].join("\n");
}

export function projectReadmeFile(projectName: string): string {
  return [
    `# ${projectName}`,
    "",
    "Canonical internal-ops starter project generated by create-plico.",
    "",
    "Start with `agent.md`, then inspect `skills/`, `tools/`, `evals/`, `memory/`, and `artifacts/`.",
    "",
  ].join("\n");
}
