import { mkdir, readdir, writeFile } from "node:fs/promises";
import { join } from "node:path";

export interface ScaffoldOptions {
  targetDir: string;
}

export async function createInternalOpsScaffold(options: ScaffoldOptions): Promise<void> {
  const root = options.targetDir;

  await ensureEmptyTarget(root);

  await mkdir(root, { recursive: true });
  await Promise.all(
    ["skills", "tools", "evals", "artifacts", "memory"].map((directory) =>
      mkdir(join(root, directory), { recursive: true }),
    ),
  );

  await writeFile(
    join(root, "plico.config.ts"),
    [
      "export default {",
      "  schemaVersion: 1,",
      '  name: "Internal Ops Agent",',
      '  template: "internal-ops",',
      "} as const;",
      "",
    ].join("\n"),
    "utf8",
  );

  await writeFile(
    join(root, "agent.md"),
    "# Internal Ops Agent\n\nFollow the project instructions.",
    "utf8",
  );

  await writeFile(
    join(root, "skills", "triage.md"),
    "# Triage\n\nReview incoming work items and classify them.",
    "utf8",
  );

  await writeFile(
    join(root, "tools", "readme.md"),
    "# Tools\n\nAdd TypeScript tool modules here.",
    "utf8",
  );

  await writeFile(join(root, "evals", "smoke.md"), "# Smoke Eval\n\nVerify the scaffold boots.", "utf8");
  await writeFile(
    join(root, "README.md"),
    "# Internal Ops Agent\n\nGenerated by create-plico.",
    "utf8",
  );
}

async function ensureEmptyTarget(root: string): Promise<void> {
  try {
    const entries = await readdir(root);
    if (entries.length > 0) {
      throw new Error(`Target directory is not empty: ${root}`);
    }
  } catch (error) {
    if (error instanceof Error && error.message.includes("ENOENT")) {
      return;
    }

    if (error instanceof Error && error.message.startsWith("Target directory is not empty")) {
      throw error;
    }

    throw error;
  }
}
