import { mkdir, readdir, writeFile } from "node:fs/promises";
import { join } from "node:path";

export interface ScaffoldOptions {
  targetDir: string;
  projectName?: string;
}

export async function createInternalOpsScaffold(options: ScaffoldOptions): Promise<void> {
  const root = options.targetDir;
  const projectName = options.projectName ?? "Internal Ops Agent";

  await ensureEmptyTarget(root);

  await mkdir(root, { recursive: true });
  await Promise.all(
    ["skills", "tools", "evals", "artifacts", "memory"].map((directory) =>
      mkdir(join(root, directory), { recursive: true }),
    ),
  );

  await writeFile(
    join(root, "plico.config.ts"),
    [
      "export default {",
      "  schemaVersion: 1,",
      `  name: ${JSON.stringify(projectName)},`,
      '  template: "internal-ops",',
      "} as const;",
      "",
    ].join("\n"),
    "utf8",
  );

  await writeFile(
    join(root, "agent.md"),
    [
      `# ${projectName}`,
      "",
      "This project is organized file-first.",
      "",
      "## Working Principles",
      "",
      "- Start from the Markdown instructions in this repository.",
      "- Use the project files as the source of truth.",
      "- Keep changes scoped and easy to validate.",
      "",
      "## First Pass",
      "",
      "- Read `plico.config.ts` and `agent.md`.",
      "- Inspect `skills/`, `tools/`, `evals/`, `artifacts/`, and `memory/`.",
      "- Add project-specific instructions before expanding the scaffold.",
      "",
    ].join("\n"),
    "utf8",
  );

  await writeFile(
    join(root, "skills", "triage.md"),
    [
      "# Triage",
      "",
      "Review incoming work items, identify the smallest safe next step, and record the outcome.",
      "",
      "Focus on the project files first, then the surrounding context.",
      "",
    ].join("\n"),
    "utf8",
  );

  await writeFile(
    join(root, "tools", "readme.md"),
    [
      "# Tools",
      "",
      "Add TypeScript tool modules here when the project needs executable helpers.",
      "",
      "Keep the public contract file-first until tools are explicitly required.",
      "",
    ].join("\n"),
    "utf8",
  );

  await writeFile(
    join(root, "evals", "smoke.md"),
    [
      "# Smoke Eval",
      "",
      "Verify the scaffold boots, validates, and presents a clear starting point.",
      "",
    ].join("\n"),
    "utf8",
  );
  await writeFile(
    join(root, "memory", "README.md"),
    [
      "# Memory",
      "",
      "Use this folder for durable project notes, decisions, and recurring context.",
      "",
    ].join("\n"),
    "utf8",
  );
  await writeFile(
    join(root, "artifacts", "README.md"),
    [
      "# Artifacts",
      "",
      "Use this folder for generated outputs that belong to the project.",
      "",
    ].join("\n"),
    "utf8",
  );
  await writeFile(
    join(root, "README.md"),
    [
      `# ${projectName}`,
      "",
      "Canonical internal-ops starter project generated by create-plico.",
      "",
      "Start with `agent.md`, then inspect `skills/`, `tools/`, `evals/`, `memory/`, and `artifacts/`.",
      "",
    ].join("\n"),
    "utf8",
  );
}

async function ensureEmptyTarget(root: string): Promise<void> {
  try {
    const entries = await readdir(root);
    if (entries.length > 0) {
      throw new Error(`Target directory is not empty: ${root}`);
    }
  } catch (error) {
    if (error instanceof Error && error.message.includes("ENOENT")) {
      return;
    }

    if (error instanceof Error && error.message.startsWith("Target directory is not empty")) {
      throw error;
    }

    throw error;
  }
}
